import { CSSProperties } from "react";

export const C = {
  bg: "#0d0d1a",
  surface: "#16213e",
  border: "#1f3460",
  accent: "#e94560",
  teal: "#64ffda",
  text: "#a8b2d8",
  white: "#eef0f8",
} as const;

export const styles: Record<string, CSSProperties> = {
  page: {
    padding: "35px 30px",
    maxWidth: "900px",
    margin: "0 auto",
    fontFamily: "'Segoe UI', sans-serif",
    color: C.text,
  },
  card: {
    backgroundColor: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: "12px",
    padding: "20px",
    marginBottom: "16px",
  },
  btn: {
    padding: "11px 24px",
    backgroundColor: C.accent,
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.95rem",
  },
  input: {
    width: "100%",
    padding: "11px 14px",
    marginBottom: "14px",
    borderRadius: "8px",
    border: `1px solid #1f3460`,
    backgroundColor: "#0d0d1a",
    color: "#eef0f8",
    fontSize: "1rem",
    boxSizing: "border-box",
    outline: "none",
  },
  code: {
    backgroundColor: "#0a0a14",
    color: "#64ffda",
    padding: "14px 18px",
    borderRadius: "8px",
    fontFamily: "Consolas, monospace",
    fontSize: "0.88rem",
    display: "block",
    margin: "10px 0 16px",
    overflowX: "auto",
    whiteSpace: "pre",
    border: `1px solid #1f3460`,
  },
  gameImage: {
    width: "100%",
    height: "200px",
    objectFit: "cover",
    display: "block",
    borderRadius: "12px 12px 0 0",
    borderBottom: `3px solid #e94560`,
    boxShadow: "0 0 12px rgba(233,69,96,0.5)",
    filter: "brightness(0.9)",
    transition: "filter 0.3s",
  },
};
